# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'OCRunnerDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Masonry'
  pod 'oc2mangoLib', :path => '../oc2mango'
  pod 'OCRunner', :path => '../'
  target 'OCRunnerDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OCRunnerDemoUITests' do
    # Pods for testing
  end

end
