# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'

target 'OCRunnerDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'MJRefresh'
  pod 'MJExtension'
  pod 'Masonry'
  pod 'ORPatchFile', :path => '../oc2mango'
  pod 'OCRunner', :path => '../'
  target 'OCRunnerDemoTests' do
    inherit! :search_paths
    pod 'oc2mangoLib', :path => '../oc2mango'
    pod 'MJExtension'
  end

  target 'OCRunnerDemoUITests' do
    # Pods for testing
  end

end

post_install do |installer|
    installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
               end
          end
   end
end
